version: '2.1'
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - ${SSD}/sonarr:/config
      - ${DATA}/tvseries:/tv
      - ${DATA}/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.30'

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - ${SSD}/radarr:/config
      - ${DATA}/movies:/movies
      - ${DATA}/downloads:/downloads
    ports:
      - 7878:7878
    deploy:
      resources:
        limits:
          cpus: '0.30'

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${SSD}/qbittorrent:/config
      - ${DATA}/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.30'

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SSD}/jellyfin:/config
      - ${DATA}/movies:/data/movies
      - ${DATA}/tvseries:/data/tvshows:ro
    ports:
      - 8096:8096
    restart: unless-stopped

  rss:
    image: pedroh1510/rss:latest
    # build: .
    container_name: rss
    ports:
      - 4000:4000
    environment:
      - port=4000
      - host=localhost
      - TZ=${TZ}
      - DATABASE_URL=file:./dev.db
    volumes:
      - ${DATA}/rss:/app/prisma/
      - ${DATA}/downloads:/app/downloads
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
