services:
  rss:
    image: pedroh1510/rss:latest
    build: .
    container_name: rss
    command: npm run server
    env_file:
      - stack.env
    volumes:
      - ${DATA}/rss/db:/app/prisma/
      - ${DATA}/rss/downloads:/app/downloads
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
    networks:
      - proxy
      - database
      - cache
      - torrent
    labels:
      - traefik.enable=true
      - traefik.http.routers.rss-router.rule=Host(`rss.${DOMAIN}`)
      - traefik.http.routers.rss-router.entrypoints=websecure
      - traefik.http.routers.rss-router.tls=true
      - traefik.http.services.rss-router.loadbalancer.server.port=4000
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
  database:
    external: true
  cache:
    external: true
  torrent:
    external: true
