services:
  rss:
    image: pedroh1510/rss:latest
    build: .
    container_name: rss
    ports:
      - 4000:4000
    environment:
      - port=4000
      - host=rss.${DOMAIN}
      - TZ=${TZ}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${DB_SCHEMA}
      - user_torrent=${TORRENT_USER}
      - pass_torrent=${TORRENT_PASS}
      - REDIS=${REDIS}
    volumes:
      - ${DATA}/rss/db:/app/prisma/
      - ${DATA}/rss/downloads:/app/downloads
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.rss-router.rule=Host(`rss.${DOMAIN}`)
      - traefik.http.routers.rss-router.entrypoints=websecure
      - traefik.http.routers.rss-router.tls=true
      - traefik.http.services.rss-router.loadbalancer.server.port=4000

networks:
  proxy:
    external: true
