services:
  database:
    image: postgres:16-alpine
    container_name: database
    ports:
      - 5432:5432
    env_file:
      - ../../../.env.development
  cache:
    image: redis:7-alpine
    container_name: cache
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
  rss:
    image: pedroh1510/rss:latest
    build: ../../../.
    container_name: rss
    ports:
      - 3333:3333
    command: npm run serverDev
    volumes:
      - ../../../src:/app/src:ro
      - ../../../tests:/app/tests:ro
      - ../../../package.json:/app/package.json:ro
    env_file:
      - ../../../.env.development
    restart: unless-stopped
