services:
  database:
    image: postgres:16-alpine
    container_name: database
    ports:
      - 5432:5432
    env_file:
      - ../../../.env.development
  cache:
    image: redis:7-alpine
    container_name: cache
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
